services:
  app:
    image: rainsho/lllcode
    restart: unless-stopped
    build:
      context: .
    ports:
      - '3333:3333'
    environment:
      - NODE_ENV=production
      - ADMIN_TOKEN=${ADMIN_TOKEN}
    volumes:
      - ./db.json:/app/db.json
